<?php require 'templates/header.phtml'; ?>

<h1 class= "text-center text-white">Fechas:</h1>
<h2 class= "text-center text-white">Seleccione una fecha:</h2>
<ul class="list-group">
    <?php foreach ($fechas as $fecha): ?>
        <a class="text-white font-weight-bold" href="https://www.virginleague.site/partidos/<?= $fecha->id_fecha ?>" class="text-decoration-none text-dark"><button class="list-group-item mb-2 text-white w-50 text-center bg-success  p-3 mx-auto">
             <?= $fecha->id_fecha ?> 
    </button></a>
    <?php endforeach ?>
</ul>
<a href="https://www.virginleague.site/temporada" class="btn btn-success"><-volver</a>

<?php require 'templates/footer.phtml' ?>