<?php require 'templates/header.phtml' ?>

    <Section class = "inicio">
        <div class = "box">
                <h1 class = "bienvenida"> Bienvenido a la pagina oficial de la liga!</h1>
        </div>
    </Section>
    <section class = "AboutUS">
        <div>
            <h2 data-aos="fade-up" class = "text-center text-white">sobre nosotros:</h2>
        </div>

        <p data-aos="fade-up" class="text-white text-center">Somos un grupo de estudiantes apasionados por el fútbol y la camaradería, unidos por una tradición que ha trascendido el tiempo y se ha convertido en uno de los pilares de nuestra vida en <b>"Las Residencias Universitarias"</b>. Inspirados por nuestro amor por el juego <i><b>Pro Evolution Soccer 06</b></i>, decidimos crear algo más que simples partidos casuales entre amigos; formamos <b>La Virgin League</b>, una liga que, a lo largo de sus ediciones, se ha convertido en un símbolo de unión, competitividad y, sobre todo, amistad.<br>
        <br>

        La idea de fundar La Virgin League nació de muchas tardes de risas, emociones y grandes jugadas frente a la pantalla, mientras compartíamos no solo nuestro fanatismo por el fútbol, sino también los momentos de convivencia y compañerismo en este lugar que hemos llegado a considerar nuestro segundo hogar. Lo que comenzó como un simple pasatiempo entre estudiantes rápidamente evolucionó hacia algo más grande y significativo. La Virgin League no es solo un torneo, es una celebración del espíritu deportivo y de la hermandad que compartimos.<br>
        <br>

        Cada edición de la liga está llena de emociones, no solo por los goles o las victorias, sino por la oportunidad de fortalecer nuestros lazos, apoyarnos mutuamente y, en el proceso, crear recuerdos que durarán toda la vida. La emoción de preparar cada temporada, elegir nuestros equipos, enfrentarnos en la cancha virtual y, luego, celebrar (o lamentar) los resultados, se ha convertido en una tradición que va más allá del juego. Nos ha enseñado valores como el respeto, el esfuerzo, la competencia sana, y, sobre todo, la importancia de la comunidad.<br>
        <br>

        En La Virgin League, todos somos protagonistas. Cada partido no es solo un desafío técnico o una estrategia de juego, sino una excusa para reunirnos, desconectar de las obligaciones académicas y sumergirnos en algo que nos apasiona. Aquí, en este pequeño rincón de las residencias, el fútbol virtual ha cobrado vida, trayendo consigo risas, gritos de emoción, debates apasionados y, lo más importante, la certeza de que, sin importar el resultado en el marcador, siempre habremos ganado algo más valioso: la amistad y el compañerismo.<br>
        <br>

        Este torneo, que sigue creciendo con cada nueva edición, representa el espíritu de quienes lo conformamos. No importa cuántas veces juguemos, siempre encontramos una razón para seguir adelante, mejorando como jugadores y como equipo. En cada pase, en cada tiro a puerta y en cada estrategia fallida o acertada, La Virgin League nos recuerda que la verdadera victoria está en compartir el juego con quienes nos rodean, y que, al final del día, lo que más valoramos son los momentos que compartimos juntos.<br>
        <br>

        Y así, entre amigos, goles y risas, hemos forjado un legado que quedará en la memoria de quienes han tenido el honor de formar parte de esta liga. Con cada nueva temporada, La Virgin League se renueva, pero siempre mantiene su esencia: la pasión por el fútbol, la diversión entre amigos, y el inquebrantable compañerismo que define nuestras vidas en las residencias.</p>
    </section>
    <section class = "directivos">
        <h2 data-aos="fade-up" class = "text-center text-white">Directivos:</h2>
        <div class = "Contenido_directivos">
            <img data-aos="fade-up" class="" src="./imagenes/directivos.jpeg" alt="directivos" alt="">
            <h1 data-aos="fade-up">Fausto Guaita y Santiago Marzolino</h1>
        </div>
    </section>
    <section class = "Ganador">
        <h2 data-aos="fade-up" class = "text-center text-white">Ganador Primera Temporada:</h2>
        <div class = "Contenido_ganador">
            <img data-aos="fade-up" class="" src="./imagenes/anteriorGanador.jpeg" alt="GANADOR" alt="">
            <h1 data-aos="fade-up">Esteban Raffaeli</h1>
        </div>
    </section>
    <section class = "desarrollador">
        <h2 data-aos="fade-up" class = "text-center text-white">La mente maestra:</h2>
        <div class = "Contenido_desarrollador">
            <img data-aos="fade-up" class="" src="./imagenes/menteMaestra.jpeg" alt="Desarrollador" alt="">
            <h1 data-aos="fade-up">Daniel Gongora (Niño Maravilla)</h1>
        </div>
    </section>
        

<!-- AOS JS -->
    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    <script>
        AOS.init(); // Inicializa AOS
    </script>
    </body>
</html>
<?php require 'templates/footer.phtml' ?>